samples/WOWSharp.Web/Controllers/AuthenticatorController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Framework.Internal;
using WOWSharp.BattleNet.Authenticator;
using WOWSharp.Web.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace WOWSharp.Web.Controllers
{
    /// <summary>
    /// Authenticator test controllers
    /// While it is typically not ideal to have authenticator functionality in a web page
    /// This controller and related views are created only to test and demonstrate the functionality of the authenticators library.
    /// </summary>
    public class AuthenticatorController : Controller
    {
        private readonly IAuthenticatorDataRepository _repository;
        private readonly IAuthenticator _authenticator;
        private readonly IEnrollmentClient _enrolClient;

        public AuthenticatorController(IAuthenticatorDataRepository repository, IAuthenticator authenticator, IEnrollmentClient enrollClient)
        {
            if (repository == null) throw new ArgumentNullException(nameof(repository));
            if (authenticator == null) throw new ArgumentNullException(nameof(authenticator));
            if (enrollClient == null) throw new ArgumentNullException(nameof(enrollClient));

            _repository = repository;
            _authenticator = authenticator;
            _enrolClient = enrollClient;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var data = await _repository.GetAuthenticatorsAsync();
            return View(data);
        }

        public IActionResult Restore()
        {
            return View();
        }

        

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Restore(RestoreAuthenticatorModel model)
        {
            if (ModelState.IsValid)
            {
                if (await _repository.CheckAccountNameExistsAsync(model.AccountName))
                {
                    ModelState.AddModelError(nameof(model.AccountName), "An account with that name already exists.");
                }
                else
                {
                    await _repository.AddAuthenticatorAsync(new AuthenticatorData()
                    {
                        Serial = model.Serial,
                        AccountName = model.AccountName,
                        RestoreCode = model.RestoreCode
                    });
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }

        public IActionResult Create()
        {
            ViewData.Add(nameof(CreateAuthenticatorModel.Region), AuthenticatorDefaults.Regions.Select(r => new SelectListItem() { Text = r, Value = r }).ToList());
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Create(CreateAuthenticatorModel model)
        {
            if (ModelState.IsValid)
            {
                if (await _repository.CheckAccountNameExistsAsync(model.AccountName))
                {
                    ModelState.AddModelError(nameof(model.AccountName), "An account with that name already exists.");
                }
                else
                {
                    await _repository.AddAuthenticatorAsync(new AuthenticatorData()
                    {
                        RegionCode = model.Region,
                        AccountName = model.AccountName
                    });
                    return RedirectToAction(nameof(Index));
                }
            }
            ViewData.Add(nameof(CreateAuthenticatorModel.Region), AuthenticatorDefaults.Regions.Select(r => new SelectListItem() { Text = r, Value = r }));
            return View(model);
        }

        public Task<AuthenticatorCode> Code(string name)
        {
            return _authenticator.GetAuthenticatorCodeAsync(name);
        }

        [HttpPost]
        public async Task Sync(string name)
        {
            var result = await _repository.GetAuthenticatorByAccountNameAsync(name);
            result.ServerTimeDifference = await _enrolClient.GetServerTimeDifferenceAsync(result.RegionCode);
            await _repository.UpdateAuthenticatorAsync(result);
        }

        [HttpDelete]
        public async Task Delete(string name)
        {
            await _repository.DeleteAuthenticatorByAccountNameAsync(name);
        }
    }
}

samples/WOWSharp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - WOWSharp.Web</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/lib/bootstrap-touch-carousel/dist/css/bootstrap-touch-carousel.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
                  asp-fallback-test-class="hidden" asp-fallback-test-property="visibility" asp-fallback-test-value="hidden" />
            <link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/bootstrap-touch-carousel/0.8.0/css/bootstrap-touch-carousel.css"
                  asp-fallback-href="~/lib/bootstrap-touch-carousel/css/bootstrap-touch-carousel.css"
                  asp-fallback-test-class="carousel-caption" asp-fallback-test-property="display" asp-fallback-test-value="none" />
            <link rel="stylesheet" href="~/css/site.css" asp-file-version="true" />
        </environment>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">WOWSharp.Web</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="Authenticator" asp-action="Index">Authenticators</a></li>
                        <li><a asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2015 - WOWSharp.Web</p>
            </footer>
        </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/lib/hammer.js/hammer.js"></script>
            <script src="~/lib/bootstrap-touch-carousel/dist/js/bootstrap-touch-carousel.js"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="//ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/hammer.js/2.0.4/hammer.min.js"
                    asp-fallback-src="~/lib/hammer.js/hammer.js"
                    asp-fallback-test="window.Hammer">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/bootstrap-touch-carousel/0.8.0/js/bootstrap-touch-carousel.js"
                    asp-fallback-src="~/lib/bootstrap-touch-carousel/dist/js/bootstrap-touch-carousel.js"
                    asp-fallback-test="window.Hammer && window.Hammer.Instance">
            </script>
            <script src="~/js/site.js" asp-file-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>